# Generated by Django 5.2.3 on 2025-07-21 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='validity_period',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
